/**
 * materialize-deployment-env tests (kageops-core / open).
 *
 * `materialize-deployment-env` is open. In production the encrypted
 * `deployment_config` reader is injected by the commercial layer via
 * `setDeploymentConfigReader`; here we inject a pure in-memory reader so the
 * open engine's env-materialisation logic is exercised standalone — no
 * commercial modules, no real disk, no DB.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as os from 'node:os';
import * as fs from 'node:fs';
import * as path from 'node:path';

import {
    materializeDeploymentEnv,
    readDeploymentEnv,
    resolveAppEnvValues,
    serializeEnvFile,
    setDeploymentConfigReader,
} from '../../src/orchestrator/materialize-deployment-env';

// ── In-memory reader harness ─────────────────────────────

const PROJECT_ID = 'aaaa1111-bbbb-2222-cccc-3333dddd4444';
const REPO_PATH = '/tmp/kageops-test-repo';

let store: Map<string, Record<string, string>>;
let writtenFiles: { path: string; contents: string; mode: number }[];

beforeEach(() => {
    store = new Map<string, Record<string, string>>();
    writtenFiles = [];
    // Inject a pure reader — the open analogue of the commercial encrypted
    // deployment_config reader wired in orchestrator-bootstrap.
    setDeploymentConfigReader(async (id) => store.get(id) ?? null);
});

afterEach(() => {
    setDeploymentConfigReader(null);
});

function fakeWriteFile() {
    return async (filePath: string, contents: string, mode: number) => {
        writtenFiles.push({ path: filePath, contents, mode });
    };
}

// ── Tests ────────────────────────────────────────────

describe('materializeDeploymentEnv — write path', () => {
    it('writes .env.local with every KEY=VALUE when config is populated', async () => {
        store.set(PROJECT_ID, {
            DATABASE_URL: 'postgres://u:p@host.neon.tech/db',
            CLERK_SECRET_KEY: 'sk_test_abc',
            STRIPE_SECRET_KEY: 'sk_test_stripe',
        });

        const result = await materializeDeploymentEnv(PROJECT_ID, REPO_PATH, {
            writeFile: fakeWriteFile(),
        });

        expect(result.status).toBe('written');
        expect(result.varCount).toBe(3);
        expect(result.path).toMatch(/\.env\.local$/);
        expect(writtenFiles.length).toBe(1);
        const body = writtenFiles[0]!.contents;
        expect(body).toContain('CLERK_SECRET_KEY=sk_test_abc');
        expect(body).toContain('STRIPE_SECRET_KEY=sk_test_stripe');
        expect(body).toContain('DATABASE_URL=');
        expect(body).toContain('# Auto-generated by KageOps');
    });

    it('writes file with mode 0o600', async () => {
        store.set(PROJECT_ID, { KEY: 'value' });
        await materializeDeploymentEnv(PROJECT_ID, REPO_PATH, {
            writeFile: fakeWriteFile(),
        });
        expect(writtenFiles[0]!.mode).toBe(0o600);
    });

    it('returns status="skipped" when no deployment_config row exists', async () => {
        const result = await materializeDeploymentEnv(PROJECT_ID, REPO_PATH, {
            writeFile: fakeWriteFile(),
        });
        expect(result.status).toBe('skipped');
        expect(result.varCount).toBe(0);
        expect(result.reason).toContain('skipped');
        expect(writtenFiles).toHaveLength(0);
    });

    it('returns status="skipped" when deployment_config row is empty {}', async () => {
        store.set(PROJECT_ID, {});
        const result = await materializeDeploymentEnv(PROJECT_ID, REPO_PATH, {
            writeFile: fakeWriteFile(),
        });
        expect(result.status).toBe('skipped');
        expect(writtenFiles).toHaveLength(0);
    });

    it('returns status="error" when the reader throws', async () => {
        setDeploymentConfigReader(async () => {
            throw new Error('corrupt blob');
        });
        const result = await materializeDeploymentEnv(PROJECT_ID, REPO_PATH, {
            writeFile: fakeWriteFile(),
        });
        expect(result.status).toBe('error');
        expect(result.reason).toContain('failed to load');
    });

    it('returns status="error" when writeFile rejects', async () => {
        store.set(PROJECT_ID, { K: 'v' });
        const result = await materializeDeploymentEnv(PROJECT_ID, REPO_PATH, {
            writeFile: async () => {
                throw new Error('disk full');
            },
        });
        expect(result.status).toBe('error');
        expect(result.reason).toContain('disk full');
    });

    it('serialised contents have keys sorted alphabetically for deterministic diffs', async () => {
        store.set(PROJECT_ID, { ZEBRA: '1', ALPHA: '2', MIKE: '3' });
        await materializeDeploymentEnv(PROJECT_ID, REPO_PATH, {
            writeFile: fakeWriteFile(),
        });
        const body = writtenFiles[0]!.contents;
        const alphaIdx = body.indexOf('ALPHA=');
        const mikeIdx = body.indexOf('MIKE=');
        const zebraIdx = body.indexOf('ZEBRA=');
        expect(alphaIdx).toBeGreaterThan(0);
        expect(alphaIdx).toBeLessThan(mikeIdx);
        expect(mikeIdx).toBeLessThan(zebraIdx);
    });
});

describe('serializeEnvFile — quoting', () => {
    it('does not quote simple alphanumeric values', () => {
        const out = serializeEnvFile({ K: 'simple_value' }, ['K']);
        expect(out).toContain('K=simple_value\n');
    });

    it('quotes values containing whitespace', () => {
        const out = serializeEnvFile({ K: 'two words' }, ['K']);
        expect(out).toContain('K="two words"');
    });

    it('quotes values containing $ (would otherwise be expanded by dotenv-expand)', () => {
        const out = serializeEnvFile({ K: 'pass$word' }, ['K']);
        expect(out).toContain('K="pass$word"');
    });

    it('escapes embedded double quotes', () => {
        const out = serializeEnvFile({ K: 'has"quote' }, ['K']);
        expect(out).toContain('K="has\\"quote"');
    });

    it('escapes embedded backslashes when quoting', () => {
        const out = serializeEnvFile({ K: 'path\\with\\slash and space' }, ['K']);
        // Backslashes get doubled inside the quoted form.
        expect(out).toContain('K="path\\\\with\\\\slash and space"');
    });
});

describe('readDeploymentEnv — pure read', () => {
    it('returns the stored values without touching disk', async () => {
        store.set(PROJECT_ID, { DATABASE_URL: 'postgres://x', CLERK_SECRET_KEY: 'sk_test_x' });
        const result = await readDeploymentEnv(PROJECT_ID);
        expect(result).toEqual({
            DATABASE_URL: 'postgres://x',
            CLERK_SECRET_KEY: 'sk_test_x',
        });
    });

    it('returns null when no config exists', async () => {
        const result = await readDeploymentEnv(PROJECT_ID);
        expect(result).toBeNull();
    });
});

// ── BPF-35 — headless app-env file precedence ────────────

describe('resolveAppEnvValues — BPF-35 file source', () => {
    let envFile: string | null = null;

    afterEach(() => {
        delete process.env.KAGEOPS_APP_ENV_FILE;
        if (envFile !== null) {
            try { fs.rmSync(envFile, { force: true }); } catch { /* ignore */ }
            envFile = null;
        }
    });

    function writeAppEnvFile(content: string): string {
        const p = path.join(os.tmpdir(), `kageops-bpf35-${process.pid}-${Math.floor(performance.now())}.env`);
        fs.writeFileSync(p, content, 'utf-8');
        process.env.KAGEOPS_APP_ENV_FILE = p;
        envFile = p;
        return p;
    }

    it('prefers KAGEOPS_APP_ENV_FILE over the encrypted deployment_config', async () => {
        store.set(PROJECT_ID, { DATABASE_URL: 'postgres://from-config' });
        writeAppEnvFile('DATABASE_URL=postgres://from-file\nCLERK_SECRET_KEY=sk_test_file');

        const result = await resolveAppEnvValues(PROJECT_ID);
        expect(result).toEqual({
            DATABASE_URL: 'postgres://from-file',
            CLERK_SECRET_KEY: 'sk_test_file',
        });
    });

    it('falls back to the encrypted config when the file path is unset', async () => {
        store.set(PROJECT_ID, { DATABASE_URL: 'postgres://from-config' });
        const result = await resolveAppEnvValues(PROJECT_ID);
        expect(result).toEqual({ DATABASE_URL: 'postgres://from-config' });
    });

    it('falls back to the encrypted config when the file is unreadable', async () => {
        store.set(PROJECT_ID, { DATABASE_URL: 'postgres://from-config' });
        process.env.KAGEOPS_APP_ENV_FILE = path.join(os.tmpdir(), 'kageops-bpf35-does-not-exist.env');
        const result = await resolveAppEnvValues(PROJECT_ID);
        expect(result).toEqual({ DATABASE_URL: 'postgres://from-config' });
    });

    it('materializeDeploymentEnv writes .env.local from the file source', async () => {
        writeAppEnvFile('DATABASE_URL=postgres://from-file\nSTRIPE_SECRET_KEY=sk_test_file');
        const result = await materializeDeploymentEnv(PROJECT_ID, '/tmp/repo', {
            writeFile: fakeWriteFile(),
        });
        expect(result.status).toBe('written');
        expect(result.varCount).toBe(2);
        expect(writtenFiles[0]!.contents).toContain('DATABASE_URL=postgres://from-file');
        expect(writtenFiles[0]!.contents).toContain('STRIPE_SECRET_KEY=sk_test_file');
    });
});
